name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem
        run: docker build -f deploy/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/steam-que-inclui:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/steam-que-inclui:latest

  deploy:
    runs-on: ubuntu-latest
    environment: Production

    needs: build
    steps:
      - name: Deploy no servidor via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/deploy
            cd /home/deploy
            git pull || git clone https://github.com/seu_usuario/seu_repositorio.git .
            docker compose pull
            docker compose up -d